import { ROBOTO_FONT } from '@/lib/mui/constants';
import { MuiProvider } from '@/lib/mui/mui-provider';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Bank App',
  description: 'Generated by create deno next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={ROBOTO_FONT.variable}>
        <MuiProvider>{children}</MuiProvider>
      </body>
    </html>
  );
}
